config/routes.rb
Rails.application.routes.draw do
  root 'admin_panel#index'
  get 'admin_panel/index'

  # get 'admin/user/index'

  namespace :admin do
    resources :users
  end
  resources :leads do
    resources :phases do
      resources :comments, module: :phases
    end
    resources :comments, module: :leads
  end

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :phases

  validates :title, :client_name, :client_address, :client_email, :client_contact, :platform_used, :test_type, :user_id,
            presence: true
end

app/models/phase.rb
class Phase < ApplicationRecord
  belongs_to :lead
  has_many :comments, as: :commentable
  has_many :phase_assignments, dependent: :destroy
  has_many :users, through: :phase_assignments
  validates :phase_type, :start_date, :due_date, presence: true
end

app/models/phase_assignment.rb
class PhaseAssignment < ApplicationRecord
  belongs_to :user
  belongs_to :phase
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :leads
  has_many :phase_assignments, dependent: :destroy
  has_many :phases, through: :phase_assignments
  after_create :assign_default_role
  def assign_default_role
    add_role(:engineer) if roles.blank?
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: %i[edit update]
  def index
    # @users = User.all
  end

  def edit
    @roles = {}
    Role.all.collect do |r|
      @roles[r.name] = r.id if r.name != 'admin'
    end
  end

  def update
    @user.roles = []
    @new_role = Role.find(user_params[:role_ids].to_i)
    @user.add_role(@new_role.name)
    @user.touch
    redirect_to admin_panel_index_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :role_ids)
  end
end

app/controllers/admin_panel_controller.rb
class AdminPanelController < ApplicationController
  before_action :redirect_to_leads, only: :index

  def index
    @users = User.all
  end

  private

  def redirect_to_leads
    redirect_to leads_path unless current_user.has_role? :admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    attributes = %i[name email password password_confirmation]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end

  rescue_from Pundit::NotAuthorizedError do
    redirect_to root_url, alert: 'You do not have access to this page'
  end
end

app/controllers/comments_controller.rb
# class CommentsController < ApplicationController
#   def create
#     @comment = @commentable.comments.new(comment_params)
#     @comment.user = current_user
#     @comment.save
#     byebug
#     redirect_to @commentable, notice: 'Your comment has been saved!'
#   end

#   private

#   def comment_params
#     params.require(:comment).permit(:content)
#   end
# end

app/controllers/leads/comments_controller.rb
# class Leads::CommentsController < CommentsController
#   before_action :set_commentable

#   private

#   def set_commentable
#     @commentable = Lead.find(params[:lead_id])
#   end
# end
class Leads::CommentsController < ApplicationController
  def create
    @lead = Lead.find(params[:lead_id])
    @comment = @lead.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to lead_path(@lead), notice: 'Your comment has been saved!'
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: ['show']

  def index
    @leads = Lead.all
  end

  def show; end

  def new
    @lead = Lead.new
    authorize @lead
  end

  def create
    @lead = current_user.leads.new(lead_params)
    # byebug
    authorize @lead

    if @lead.save!
      redirect_to leads_path
    else
      render :new
    end
  end

  private

  def set_lead
    @lead = Lead.find(params[:id])
  end

  def lead_params
    params.require(:lead).permit(:title, :client_name, :client_address, :client_email, :client_contact, :platform_used,
                                 :test_type)
  end
end

app/controllers/phases/comments_controller.rb
# class Phases::CommentsController < CommentsController
#   before_action :set_commentable

#   private

#   def set_commentable
#     @commentable = Phase.find(params[:phase_id])
#   end
# end

class Phases::CommentsController < ApplicationController
  def create
    @phase = Phase.find(params[:phase_id])
    @lead = Lead.find(params[:lead_id])
    @comment = @phase.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to lead_phase_path(@lead.id, @phase.id), notice: 'Your comment has been saved!'
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/phases_controller.rb
class PhasesController < ApplicationController
  before_action :set_lead
  before_action :set_phase, only: %w[show edit update]
  before_action :set_manager, only: %w[show edit]
  before_action :set_engineers_ist, only: %w[show edit]

  def index
    @phases = @lead.phases.all
  end

  def show; end

  def new
    @phase = Phase.new
    authorize @phase
  end

  def create
    @phase = @lead.phases.new(phase_params)
    authorize @phase

    if @phase.save!
      redirect_to lead_path(@lead)
    else
      render :new
    end
  end

  def edit
    authorize @phase
    @managers = {}
    @engineers = {}
    User.all.collect do |user|
      @managers[user.name] = user.id if user.roles.first.name == 'manager'
    end

    User.all.collect do |user|
      @engineers[user.name] = user.id if user.roles.first.name == 'engineer'
    end
  end

  def update
    authorize @phase
    # byebug
    # if params[:user_ids].length > 0
    if params[:user_ids].instance_of?(Array)
      @extra = params[:user_ids]
      @extra.each do |usid|
        @user = User.find(usid)
        @assignment = PhaseAssignment.new(user_id: @user.id, phase_id: @phase.id)
        @assignment.save
      end

    else
      @user = User.find(phase_params[:user_ids].to_i)
      @assignment = PhaseAssignment.new(user_id: @user.id, phase_id: @phase.id)
      UserMailer.example(@user).deliver
    end
    redirect_to lead_phase_path(@lead.id, @phase.id)
    # if @assignment.save
    # else
    #   render :edit
    # end
    # if @phase.update(book_params)
    #   redirect_to book_path
    # else
    #   render :new
    # end
  end

  private

  def set_manager
    @assigned_user = PhaseAssignment.where(phase_id: @phase.id)
    @assigned_manager = User.find(@assigned_user.first.user_id) unless @assigned_user.empty?
  end

  def set_engineers_ist
    @assigned_engineer = PhaseAssignment.where(phase_id: @phase.id)
    @assigned_engineer_arr = []
    @assigned_engineer.each do |engnr|
      @assigned_engineer_arr << User.find(engnr.user_id) unless @assigned_engineer.empty?
    end
  end

  def set_lead
    @lead = Lead.find(params[:lead_id].to_i)
  end

  def set_phase
    @phase = Phase.find(params[:id])
  end

  def phase_params
    params.require(:phase).permit(:phase_type, :start_date, :due_date, :user_ids, :engineer_idass)
  end
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/phases_helper.rb
module PhasesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/users/edit.html.erb
<%= form_for [:admin, @user] do |form|%>

<div>
<%= form.label :email%><br>
<%= form.text_field :email, :readonly => true%>
</div>

<div class="mt-3">
<%= form.label :name%><br>
<%= form.text_field :name, :readonly => true%>
</div>

<div class="mb-5 mt-3">
  <p> Role: </p>
  <%= form.select :role_ids,options_for_select(@roles, @user.roles.collect {|d| d.id }) %>

</div>

<div>
<%= form.submit %>
</div>


<% end %>

app/views/admin/users/index.html.erb
<h1>admin/User#index</h1>

app/views/admin_panel/index.html.erb
  <% if current_user.has_role? :admin %>
    <div class="d-flex justify-content-center align-items-center">
        <h1>Admin Panel</h1>
    </div>
    <h1>Users</h1>
    <div class="row ">
        <% @users.each do |user|%>
          <div class="card mb-2 ml-3 mr-3 " style="width: 18rem;">
            <div class="card-body bg-dark text-white">
              <h5 class="card-title">Name :<%= user.name %></h5>
              <p class="card-text"><b>Email : </b><%= user.email%></p>
              <p class="card-text"><b>UID : </b><%= user.id%></p>
              <div class="card-text">

                          <% user.roles.each do |role|%>
                          <p> <b>Role : </b> <%= role.name %> </p>

                          <% end %>
              </div>
                <% if !(user.has_role? :admin) %>
                  <div class="btn  bg-light">
                  <%= link_to "Edit", edit_admin_user_path(user) if !(user.has_role? :admin)%>
                  </div>
                <% end %>
            </div>
          </div>
        <% end %>
    </div>
  <% else %>
  <div class="d-flex justify-content-center align-items-center">
        <h1>Coming Soon</h1>
    </div>

  <% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ commentable, commentable.comments.build ] do |form| %>
  <p>
      <h5> User: <%= current_user.name%> </h5>
  </p>

  <p>
    <%= form.label :comment %><br>
    <%= form.text_area :content, placeholder: "Add a comment"%>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/leads/_form.html.erb
<%= form_with model: lead do |form|%>
<div>
  <%= form.label :title%><br>
  <%= form.text_field :title%>
    <% lead.errors.full_messages_for(:title).each do |message|%>
    <div><%= message%> </div>

    <%end%>
</div>

<div>
  <%= form.label :client_name%><br>
  <%= form.text_field :client_name%>
    <% lead.errors.full_messages_for(:client_name).each do |message|%>
    <div><%= message%> </div>

    <%end%>
</div>

<div>
  <%= form.label :client_address%><br>
  <%= form.text_area :client_address%>
    <% lead.errors.full_messages_for(:client_address).each do |message|%>
      <div><%= message%> </div>

    <%end%>
</div>

<div>
  <%= form.label :client_email%><br>
  <%= form.text_field :client_email%>
    <% lead.errors.full_messages_for(:client_email).each do |message|%>
    <div><%= message%> </div>

    <%end%>
</div>

<div>
  <%= form.label :client_contact%><br>
  <%= form.text_field :client_contact%>
    <% lead.errors.full_messages_for(:client_contact).each do |message|%>
    <div><%= message%> </div>

    <%end%>
</div>

<div>
  <%= form.label :platform_used%><br>
  <%= form.text_field :platform_used%>
    <% lead.errors.full_messages_for(:platform_used).each do |message|%>
    <div><%= message%> </div>

    <%end%>
</div>

<div>
  <%= form.label :test_type%><br>
  <%= form.text_field :test_type%>
    <% lead.errors.full_messages_for(:test_type).each do |message|%>
      <div><%= message%> </div>

    <%end%>
</div>

<div>
<%= form.submit%>
</div>


<% end %>

app/views/leads/index.html.erb
<div class="d-flex justify-content-center align-items-center">
    <h1> Leads! </h1>
</div>

  <% @leads.each do |lead|%>
       <h3>Title: <%= link_to lead.title, lead %> </h3>
        <p> Client: <%= lead.client_name%> </p>
  <% end %>

<%= link_to "New Lead", new_lead_path%>

app/views/leads/new.html.erb
<h1> Create New Lead </h1>

<%= render "form", lead: @lead %>

app/views/leads/show.html.erb
<div class="card mt-2 bg-secondary text-light" style="width: 44rem; border-color:"black"">
  <div class="card-body">
    <h5 class="card-title">Created By: <%= @lead.user.name %></h5>
    <h5 class="card-title">Title: <%= @lead.title %></h5>
    <p class="card-text">Client Name: <%= @lead.client_name %></p>
    <p class="card-text">Client Address: <%= @lead.client_address %></p>
    <p class="card-text">Client Email: <%= @lead.client_email %></p>
    <p class="card-text">Client Contact: <%= @lead.client_contact %></p>
    <p class="card-text">Platform Used:<%= @lead.platform_used %></p>
    <p class="card-text">Test Type: <%= @lead.test_type %></p>
  </div>
</div>
<p> <%= link_to "Create new phase", new_lead_phase_path(@lead.id)%> </p>
<p> <%= link_to "Phases", lead_phases_path(@lead)%> </p>
<%= render partial: "shared/comments", locals: {commentable: @lead}%>

<h5>Add a comment below</h5>
<%= render partial: 'shared/form',  locals: {commentable: @lead, path_prefix: nil}%>

app/views/phases/edit.html.erb
<%= form_with model:[@lead, @phase] do |form|%>

  <div>
    <%= form.label :phase_type%><br>
    <%= form.text_field :phase_type, :readonly => true%>
  </div>

  <div class="mt-3">
    <%= form.label :start_date%><br>
    <%= form.text_field :start_date, :readonly => true%>
  </div>

  <div class="mt-3">
    <%= form.label :due_date%><br>
    <%= form.text_field :due_date, :readonly => true%>
  </div>
<%# <%byebug%> %>
  <div class="mb-5 mt-3">
    <p> Role: </p>
    <% if @assigned_manager != nil %>
        <span><b> Manager: </b> <%= @assigned_manager.name%> </span>
        <div class="field mb-3">
        <%= form.label :user_ids %><br>
        <%= select_tag :user_ids,
              options_for_select(@engineers, selected: @engineers.first),
              multiple: true %>

        </div>
    <% else %>
        <%= form.select :user_ids,options_for_select(@managers),selected: @managers.first %>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/phases/index.html.erb
<div class="d-flex justify-content-center align-items-center">
    <h1> Phases for Lead # <%= @lead.id%> </h1>
</div>

  <% @phases.each do |phase|%>
       <h3>Title: <%= link_to phase.phase_type, lead_phase_path(@lead.id, phase.id) %> </h3>
        <p> Start Date: <%= phase.start_date %> </p>
        <p> End Date: <%= phase.due_date %> </p>
  <% end %>

app/views/phases/new.html.erb
<h1> You can create new a phase here! </h1>

<h3> Phase for Lead: <%= @lead.id %></h3>

<%= form_with model: [@lead, @phase] do |form|%>
<div>
  <%= form.label :phase_type%><br>
  <%= form.text_field :phase_type%>
    <% @phase.errors.full_messages_for(:phase_type).each do |message|%>
    <div><%= message%> </div>

    <%end%>
</div>

<div>
  <%= form.label :start_date, class: "mb-0 mt-2"%><br>
  <%= form.date_field :start_date, as: :date, value: params[:start_date], placeholder: "yyyy-mm-dd", class: "mb-2"%>
    <% @phase.errors.full_messages_for(:start_date).each do |message|%>
    <div><%= message%> </div>

    <%end%>
</div>

<div>
  <%= form.label :due_date, class: "mb-0 mt-2" %><br>
  <%= form.date_field :due_date,  as: :date, value: params[:due_date], placeholder: "yyyy-mm-dd", class: "mb-2"%>
    <% @phase.errors.full_messages_for(:due_date).each do |message|%>
      <div><%= message%> </div>

    <%end%>
</div>


<div>
<%= form.submit%>
</div>


<% end %>

app/views/phases/show.html.erb
<h3>WElcome to show of Phase <%= @phase.id%> </h3>

       <h3>Title: <%= @phase.phase_type %> </h3>
        <p> Start Date: <%= @phase.start_date %> </p>
        <p> End Date: <%= @phase.due_date %> </p>
        <p> <b> Assigned Manager:</b>
                <%  if @assigned_manager != nil %>
                        <%= @assigned_manager.name%>
                <% else %>
                        <span> Not assigned yet! </span>
                <% end %>
        </p>
        <% byebug %>
        <p> <b> Assigned Engineers:</b> </p>
        <% @assigned_engineer_arr.each do |engnr|%>
        <p> <%= engnr.name if engnr.roles.first.name != "manager" %> </p>
        <% end %>
        <% if @phase.phase_assignments.empty? %>
                <%= link_to "Edit", edit_lead_phase_path(@lead.id, @phase.id) %>
        <% end %>
<%= render partial: "shared/comments", locals: {commentable: @phase}%>

<h5>Add a comment below</h5>
<%= render partial: 'shared/form', locals: {commentable: @phase, path_prefix: @lead}%>